AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-example-cron

  Sample SAM Template for sam-example-cron

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      Architectures:
      - x86_64
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0/5 * * * ? *)
